version: '3.4'

services:
  db:
    image: mysql:5
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql/
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: BA
  app:
    image: ba-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8026:8000"
    volumes:

      # - .:/code
      - ./BAProject:/app

      - static:/app/static
      - media:/app/media


volumes:
  static:
  media:
